name: Build and deploy to GitHub Pages

on:
  push:
    branches: ["gh-pages"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    if: >
      !(
        github.event_name == 'push' &&
        github.run_attempt == 1 &&
        (
          contains(github.event.head_commit.message, '@@__LNN_NO_BUILD__@@') ||
          (
            github.event.head_commit.author.name == 'dependabot[bot]' &&
            contains(github.event.head_commit.message, 'updated-dependencies:')
          )
        )
      )
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build site assets
        run: yarn build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
